services: # The services available
  publisher: # Service 1: Publisher
    # Make docker build the image using dockerfile
    build: 
      context: ./redis_publisher
      dockerfile: Dockerfile
    environment:
      - redis_host=172.30.1.3
      - redis_port=6379
    ports: 
      - 8080:8080 # Only port 8080 because it is used by the app
    networks:
      internal:
        ipv4_address: 172.30.1.2
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - "6379:6379"
    networks:
      internal:
        ipv4_address: 172.30.1.3

# For isolating the network
networks:
  internal:
    name: nwdaf_subnet
    ipam:
      config:
        - subnet: 172.30.1.0/24